# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */4 * * *'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Install dependencies
      run: pip install requests
    - name: Get and store data
      run: python3 convert2json.py > data/mortalita_provincia.json
    - name: Setup git
      run: git config user.name "${GITHUB_ACTOR}" && git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" 
    - name: Commit data
      run: git add data/mortalita_provincia.json && git commit -m "$(date)"
    - name: Push data
      run: git push origin master
